# Generated by Django 6.0.3 on 2026-03-15 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('contract_type', models.CharField(choices=[('employment_contract', 'Employment Contract'), ('offer_letter', 'Offer Letter'), ('addendum', 'Contract Addendum'), ('other', 'Other')], default='employment_contract', max_length=50)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('raw_text', models.TextField(blank=True)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('basic_salary', models.CharField(blank=True, max_length=100)),
                ('gross_salary', models.CharField(blank=True, max_length=100)),
                ('contract_duration', models.CharField(blank=True, max_length=100)),
                ('probation_period', models.CharField(blank=True, max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_risk', models.CharField(blank=True, choices=[('valid', 'Valid'), ('attention', 'Requires Attention'), ('high_risk', 'High Risk')], max_length=20)),
                ('compliance_score', models.IntegerField(blank=True, null=True)),
                ('compliant_count', models.IntegerField(default=0)),
                ('attention_count', models.IntegerField(default=0)),
                ('non_compliant_count', models.IntegerField(default=0)),
                ('missing_clauses_count', models.IntegerField(default=0)),
                ('executive_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClauseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('parties', 'Contract Parties'), ('job_title', 'Job Title'), ('workplace', 'Workplace'), ('salary', 'Salary & Allowances'), ('duration', 'Contract Duration'), ('probation', 'Probation Period'), ('working_hours', 'Working Hours'), ('vacation', 'Vacation & Leave'), ('overtime', 'Overtime'), ('termination', 'Contract Termination'), ('compensation', 'Compensation & End of Service'), ('confidentiality', 'Confidentiality'), ('non_compete', 'Non-Competition'), ('deductions', 'Salary Deductions & Penalties'), ('transfer', 'Employee Transfer'), ('medical_insurance', 'Medical Insurance'), ('renewal', 'Contract Renewal'), ('start_date', 'Start Date'), ('other', 'Other')], max_length=50)),
                ('clause_title', models.CharField(max_length=255)),
                ('clause_text', models.TextField(blank=True)),
                ('assessment', models.CharField(choices=[('compliant', 'Compliant'), ('needs_clarification', 'Needs Clarification'), ('may_non_compliant', 'May Be Non-Compliant'), ('missing', 'Missing Clause'), ('ambiguous', 'Ambiguous'), ('unusual', 'Unusual Clause')], max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='low', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('regulatory_reference', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
            ],
            options={
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='MissingClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_name', models.CharField(max_length=255)),
                ('importance', models.CharField(choices=[('required', 'Required by Law'), ('recommended', 'Recommended'), ('optional', 'Optional but Beneficial')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('regulatory_reference', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_clauses', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('related_clause', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_questions', to='contracts.contract')),
            ],
        ),
    ]
